type Message {
    _id: ID
    message: String
    author: String
    time: String
    chat: Chat
}

type Chat {
    _id: ID
    name: String
    users: [String]
    messages: [Message]  
}

type Query {
    getChatById(id: ID!): Chat
    getAllChats(userId: ID!): [Chat]
}

input CreateChatInput {
    name: String
}

input CreateMessageInput {
    message: String
    author: String
    chat: ID
}

type Mutation {
    createChat(createChatInput: CreateChatInput!): Boolean
    createMessage(createMessageInput: CreateMessageInput!): Boolean
    updateChat(chatId: ID!, name: String!): Boolean 
    updateMessage(messageId: ID!, message: String!): Boolean
    deleteChat(chatId: ID!): Boolean
    deleteMessage(messageId: ID!): Boolean
}