type Message {
    _id: ID
    message: String
    author: String
    time: String
    chat: Chat
}

type Chat {
    _id: ID
    name: String
    users: [String]
    messages: [Message]  
}

type Query {
    getChatById(id: ID!): Chat
    getAllChats(userId: ID!): [Chat]
}

input CreateChatInput {
    name: String
}

type Mutation {
    createChat(createChatInput: CreateChatInput!): Boolean
    updateChat(chatId: ID!, name: String!): Boolean 
}